name: docs

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Install python 3.x 
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # https://github.com/actions/cache/blob/main/examples.md#python---pip
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('doc/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r doc/requirements.txt
      # Build documentation under ${PWD}/_build
      - name: Build Sphinx docs
        run: |
          make BUILDDIR=${PWD}/_build -C doc/ html
      - name: Push PR preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: './_build/html'
          destination_dir: './branch/${{ github.event.pull_request.head.ref }}'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
      - name: Comment about previewing documentation
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v6
        with:
          script: |
            var comments = await github.paginate(github.rest.issues.listComments, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            console.log(comments);

            # var havePosted = comments.map(x => x.user.login).some(x => x === "github-actions[bot]");

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'You can preview documentation at https://esmci.github.io/cime/branch/${{ github.event.pull_request.head.ref }}/index.html'
            })
